"""empty message

Revision ID: 3e4685309f78
Revises: 2daf82e00e22
Create Date: 2022-06-06 21:48:09.726649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4685309f78'
down_revision = '2daf82e00e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'seek_description',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    op.alter_column('venue', 'seek_description',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'seek_description',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    op.alter_column('artist', 'seek_description',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    # ### end Alembic commands ###
